### ISSUE TITLE
Neurosymbolic prediction method not working with HF model (yet)

### ISSUE THREAD

**Issue by menamerai** [menamerai/linc#2]
Run `main` code in `lm.py` to see the neurosymbolic example. Make sure it's what you expected for the sympy functions @arnavkomaragiri

**Comment by arnavkomaragiri** [comment]
I implemented the symbolic logic prover so that's working, I'm just not sure what format the LM will be exporting the FOL expressions in. Once we have that it's really just parsing out the individual FOL expressions/conclusions and passing them off to the symbolic logic prover.
